SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

FPS = 60

BLACK = ((0, 0, 0))

PLAYER_WIDTH = 64
PLAYER_HEIGHT = 32
PLAYER_IMAGE = "images\\player.png"
PLAYER_START_X = SCREEN_WIDTH / 2
PLAYER_START_Y = SCREEN_HEIGHT
PLAYER_SPEED = 6

WEAPON_COOLDOWN = 200